### ISSUE TITLE
new release needed for 0.18

### ISSUE THREAD

**Issue by martindemello** [tortus/elm-array-2d#1]
The latest release tag (2.01) points to a commit before the update to elm 0.18. Could you push out a new release?

**Comment by wmakley** [comment]
I'm not sure how that happened, but I'm not very good with git tags. I just hoped elm package publish would take care of it. Anyway, I've bumped the version and added a new correct tag for 2.0.2, but my attempts to publish are timing out right now. I will do so as soon as possible.

**Comment by wmakley** [comment]
That should do it!

**Comment by martindemello** [comment]
thanks for the quick fix!

**Comment by wmakley** [comment]
Do you actually use it for something?

**Comment by martindemello** [comment]
yep, i use it to represent a crossword grid.

https://github.com/martindemello/crosspad.elm/blob/master/src/elm/Xword.elm

**Comment by wmakley** [comment]
cool!
